# Neck
- type: loadout
  id: HosSpecialCloak
  equipment:
    neck: ClothingNeckHosSpecialCloak

- type: loadout
  id: HeadofSecurityCeremonialCloak
  equipment:
    neck: ClothingNeckCloakBattleHoS

# Belt
- type: loadout
  id: SecuritySheathBelt
  equipment:
    belt: ClothingSheathBeltSecurityFilled

#Backpack
- type: loadout
  id: HeadofSecurityBackpack
  equipment:
    back: ClothingBackpackBattleHoSPack

# Back
- type: loadout
  id: HeadofSecurityDuffel
  equipment:
    back: ClothingBackpackDuffelHoSDuf

- type: loadout
  id: HeadofSecuritySatchel
  equipment:
    back: ClothingBackpackSatchelBattleHoSSat

# Suit
- type: loadout
  id: HeadofSecurityJumpsuitElegant
  equipment:
    jumpsuit: ClothingUniformJumpskirtElegantHos
    neck: ClothingNeckCloakBattleHoS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS100h

# OuterClothing
- type: loadout
  id: HeadofSecurityTrenchElegant
  equipment:
    outerClothing: ClothingOuterHoSTrenchElegant
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS100h
