# Neck
- type: loadout
  id: HosSpecialCloak
  equipment:
    neck: ClothingNeckHosSpecialCloak

- type: loadout
  id: HeadofSecurityCeremonialCloak
  equipment:
    neck: ClothingNeckCloakBattleHoS

# Belt
- type: loadout
  id: SecuritySheathBelt
  equipment:
    belt: ClothingSheathBeltSecurityFilled

#Backpack
- type: loadout
  id: HeadofSecurityBackpack
  equipment:
    back: ClothingBackpackBattleHoSPack

# Back
- type: loadout
  id: HeadofSecurityDuffel
  equipment:
    back: ClothingBackpackDuffelHoSDuf

- type: loadout
  id: HeadofSecuritySatchel
  equipment:
    back: ClothingBackpackSatchelBattleHoSSat

# Suit
- type: loadout
  id: HeadofSecurityJumpsuitElegant
  equipment:
    neck: ClothingNeckCloakBattleHoS

# OuterClothing
- type: loadout
  id: HeadofSecurityTrenchElegant
  equipment:
    outerClothing: ClothingOuterHoSTrenchElegant
    jumpsuit: ClothingUniformJumpskirtElegantHos
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 360000 #100 hrs
